const data = document.querySelector("#data")
const imagem = document.querySelector("#imagem")
const titulo = document.querySelector("#titulo")
const autor = document.querySelector("#autor")
const explicacao = document.querySelector("#explicacao")